FROM golang:1.25.0-trixie AS builder

WORKDIR /nta

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /adapter ./nta

FROM debian:bookworm-slim AS runtime

WORKDIR /nta

COPY --from=builder /adapter .

ENTRYPOINT ["./adapter"]